package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Saturday, March 18, 2023 12:42:40 PM ICT
*/

public interface HelloOperations 
{
  String getListCustomer ();
  String getDetailCustomer ();
} // interface HelloOperations
